#!/usr/bin/env python3
"""
SWARMZ Theorem Knowledge Base — Setup
══════════════════════════════════════
Creates theorem_kb/ folder, writes raw_theorems.txt with the full
list of notable theorems, parses them into structured JSON, and
generates per-category index files.

Usage:
    python setup_theorem_kb.py
"""

import re
import json
from pathlib import Path
from datetime import datetime

# ── paths ────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent
KB_DIR = ROOT / "theorem_kb"
RAW_FILE = KB_DIR / "raw_theorems.txt"
PARSED_FILE = KB_DIR / "theorems.json"
INDEX_FILE = KB_DIR / "index.json"
CATEGORIES_DIR = KB_DIR / "categories"

# ── regex ────────────────────────────────────────────────────────────
THEOREM_RE = re.compile(r"^(?P<name>.+?)\s*\((?P<fields>[^)]+)\)\s*$")

# ────────────────────────────────────────────────────────────────────
# RAW THEOREM CORPUS  (embedded so the script is fully self-contained)
# ────────────────────────────────────────────────────────────────────
RAW_THEOREMS = r"""Logics and foundations
Ax-Grothendieck theorem (model theory)
Barwise compactness theorem (mathematical logic)
Borel determinacy theorem (set theory)
Buchi-Elgot-Trakhtenbrot theorem (mathematical logic)
Cantor-Bernstein-Schroder theorem (set theory, cardinal numbers)
Cantor's theorem (set theory)
Church-Rosser theorem (lambda calculus)
Compactness theorem (mathematical logic)
Conservativity theorem (mathematical logic)
Craig's theorem (mathematical logic)
Craig's interpolation theorem (mathematical logic)
Cut-elimination theorem (proof theory)
Deduction theorem (logic)
Diaconescu's theorem (mathematical logic)
Easton's theorem (set theory)
Erdos-Dushnik-Miller theorem (set theory)
Erdos-Rado theorem (set theory)
Feferman-Vaught theorem (model theory)
Friedberg-Muchnik theorem (mathematical logic)
Fundamental theorem of equivalence relations (set theory)
Glivenko's theorem (mathematical logic)
Gentzen's consistency proof (proof theory)
Godel's completeness theorem (mathematical logic)
Godel's incompleteness theorem (mathematical logic)
Goodstein's theorem (mathematical logic)
Herbrand's theorem (logic)
Independence of the axiom of choice (mathematical logic)
Independence of the continuum hypothesis (mathematical logic)
Kanamori-McAloon theorem (mathematical logic)
Kirby-Paris theorem (proof theory)
Kleene's recursion theorem (recursion theory)
Konig's theorem (set theory, mathematical logic)
Lindstrom's theorem (mathematical logic)
Lob's theorem (mathematical logic)
Los' theorem (model theory)
Lowenheim-Skolem theorem (mathematical logic)
Matiyasevich's theorem (mathematical logic)
Morley's categoricity theorem (model theory)
Paris-Harrington theorem (mathematical logic)
Post's theorem (mathematical logic)
Richardson's theorem (mathematical logic)
Robinson's joint consistency theorem (mathematical logic)
Sahlqvist correspondence theorem (modal logic)
Soundness theorem (mathematical logic)
Tarski's indefinability theorem (mathematical logic)
Tennenbaum's theorem (model theory)
Uncountability of the continuum (set theory)
Well-ordering theorem (mathematical logic)
Wilkie's theorem (model theory)
Zorn's lemma (set theory)

Combinatorics
2-factor theorem (graph theory)
Abel's binomial theorem (combinatorics)
Alspach's theorem (graph theory)
Aztec diamond theorem (combinatorics)
BEST theorem (graph theory)
Baranyai's theorem (combinatorics)
Berge's theorem (graph theory)
Binomial theorem (algebra, combinatorics)
Bondy's theorem (graph theory, combinatorics)
Bondy-Chvatal theorem (graph theory)
Brooks's theorem (graph theory)
Bruck-Chowla-Ryser theorem (combinatorics)
Cameron-Erdos theorem (discrete mathematics)
Corners theorem (arithmetic combinatorics)
Courcelle's theorem (graph theory)
De Bruijn-Erdos theorem (graph theory)
Dirac's theorems (graph theory)
Erdos-Gallai theorem (graph theory)
Erdos-Ginzburg-Ziv theorem (number theory)
Erdos-Ko-Rado theorem (combinatorics)
Erdos-Posa theorem (graph theory)
Erdos-Stone theorem (graph theory)
Euler's partition theorem (number theory)
Fermat polygonal number theorem (number theory)
Five color theorem (graph theory)
Four color theorem (graph theory)
Freiman's theorem (number theory)
Friendship theorem (graph theory)
Galvin's theorem (combinatorics)
Gomory's theorem (combinatorics)
Graph structure theorem (graph theory)
Grinberg's theorem (graph theory)
Grotzsch's theorem (graph theory)
Hajnal-Szemeredi theorem (graph theory)
Hales-Jewett theorem (combinatorics)
Hall's marriage theorem (combinatorics)
Halpern-Lauchli theorem (Ramsey theory)
Hindman's theorem (Ramsey theory)
Kirchhoff's theorem (graph theory)
Kneser's theorem (combinatorics)
Konig's theorem (bipartite graphs)
Kovari-Sos-Turan theorem (graph theory)
Kruskal-Katona theorem (combinatorics)
Kuratowski's theorem (graph theory)
Lambek-Moser theorem (combinatorics)
MacMahon's master theorem (enumerative combinatorics)
Menger's theorem (graph theory)
Milliken-Taylor theorem (Ramsey theory)
Milliken's tree theorem (Ramsey theory)
Multinomial theorem (algebra, combinatorics)
Mycielski's theorem (graph theory)
Nicomachus's theorem (number theory)
Ore's theorem (graph theory)
Paley's theorem (algebra)
Perfect graph theorem (graph theory)
Perlis theorem (graph theory)
Planar separator theorem (graph theory)
Polya enumeration theorem (combinatorics)
Ramsey's theorem (graph theory, combinatorics)
Ringel-Youngs theorem (graph theory)
Robbins' theorem (graph theory)
Robertson-Seymour theorem (graph theory)
Schnyder's theorem (graph theory)
Schur's theorem (Ramsey theory)
Schwenk's theorem (graph theory)
Sensitivity theorem (computational complexity theory)
Sperner's theorem (combinatorics)
Stanley's reciprocity theorem (combinatorics)
Star of David theorem (combinatorics)
Stirling's theorem (mathematical analysis)
Strong perfect graph theorem (graph theory)
Symmetric hypergraph theorem (graph theory)
Szemeredi's theorem (combinatorics)
Theorem on friends and strangers (Ramsey theory)
Tutte's theorem on perfect matchings (graph theory)
Turan's theorem (graph theory)
Van der Waerden's theorem (combinatorics)
Vizing's theorem (graph theory)
Wagner's theorem (graph theory)
Zeilberger-Bressoud theorem (combinatorics)

Order, lattices, ordered algebraic structures
Birkhoff's representation theorem (lattice theory)
Boolean prime ideal theorem (mathematical logic)
Bourbaki-Witt theorem (order theory)
Cantor's isomorphism theorem (order theory)
Dilworth's theorem (combinatorics, order theory)
Four functions theorem (combinatorics)
Hahn embedding theorem (ordered groups)
Hausdorff maximality theorem (set theory)
Kleene fixed-point theorem (order theory)
Knaster-Tarski theorem (order theory)
Kruskal's tree theorem (order theory)
Shannon's expansion theorem (Boolean algebra)
Stone's representation theorem for Boolean algebras (mathematical logic)
Szpilrajn extension theorem (axiom of choice)

General algebraic systems
Fundamental theorem on homomorphisms (abstract algebra)
Isomorphism theorem (abstract algebra)
Lattice theorem (abstract algebra)

Number theory
15 and 290 theorems (number theory)
Albert-Brauer-Hasse-Noether theorem (algebras)
Ankeny-Artin-Chowla theorem (number theory)
Apery's theorem (number theory)
Artin-Verdier duality theorem (number theory)
ATS theorem (number theory)
Auxiliary polynomial theorem (Diophantine approximation)
Ax-Kochen theorem (number theory)
Baker's theorem (number theory)
Barban-Davenport-Halberstam theorem (analytic number theory)
Basel problem (mathematical analysis)
Beatty's theorem (Diophantine approximation)
Behrend's theorem (number theory)
Bertrand's postulate (number theory)
Birch's theorem (algebraic number theory)
Bombieri's theorem (number theory)
Bombieri-Friedlander-Iwaniec theorem (number theory)
Brauer-Siegel theorem (number theory)
Brun's theorem (number theory)
Brun-Titchmarsh theorem (number theory)
Carmichael's theorem (Fibonacci numbers)
Chebotarev's density theorem (number theory)
Chen's theorem (number theory)
Chowla-Mordell theorem (number theory)
Cohn's irreducibility criterion (polynomials)
Critical line theorem (number theory)
Davenport-Schmidt theorem (number theory, Diophantine approximations)
Dirichlet's approximation theorem (Diophantine approximations)
Dirichlet's theorem on arithmetic progressions (number theory)
Dirichlet's unit theorem (algebraic number theory)
Equidistribution theorem (ergodic theory)
Erdos-Kac theorem (number theory)
Euclid's theorem (number theory)
Euclid-Euler theorem (number theory)
Euler's theorem (number theory)
Fermat's Last Theorem (number theory)
Fermat's little theorem (number theory)
Fermat's theorem on sums of two squares (number theory)
Ferrero-Washington theorem (algebraic number theory)
Ford's theorem (number theory)
Franel-Landau theorem (number theory)
Gelfond-Schneider theorem (transcendental number theory)
Glaisher's theorem (number theory)
Green-Tao theorem (number theory)
Gross-Zagier theorem (number theory)
Grunwald-Wang theorem (algebraic number theory)
Hardy-Ramanujan theorem (number theory)
Hasse norm theorem (number theory)
Hasse-Minkowski theorem (number theory)
Herbrand-Ribet theorem (cyclotomic fields)
Hilbert-Speiser theorem (cyclotomic fields)
Hilbert-Waring theorem (number theory)
Hilbert's irreducibility theorem (number theory)
Hurwitz's theorem (number theory)
Jacobi's four-square theorem (number theory)
Jurkat-Richert theorem (analytic number theory)
Kaplansky's theorem on quadratic forms (number theory)
Khinchin's theorem (probability)
Kronecker's theorem (Diophantine approximation)
Kronecker-Weber theorem (number theory)
Kummer's theorem (number theory)
Lafforgue's theorem (algebraic number theory)
Lagrange's four-square theorem (number theory)
Landau prime ideal theorem (number theory)
Lindemann-Weierstrass theorem (transcendental number theory)
Linnik's theorem (number theory)
Lochs's theorem (number theory)
Lucas's theorem (number theory)
Mahler's compactness theorem (geometry of numbers)
Mahler's theorem (p-adic analysis)
Maier's theorem (analytic number theory)
Mann's theorem (number theory)
Mazur's control theorem (number theory)
Mertens's theorems (number theory)
Midy's theorem (number theory)
Mihailescu's theorem (number theory)
Mirsky-Newman theorem (group theory)
Modularity theorem (number theory)
Mordell-Weil theorem (number theory)
Multiplicity-one theorem (group representations)
Nagell-Lutz theorem (elliptic curves)
Niven's theorem (number theory)
Ostrowski's theorem (number theory)
Pentagonal number theorem (number theory)
Prime number theorem (number theory)
Principal ideal theorem (algebraic number theory)
Proth's theorem (number theory)
Quadratic reciprocity theorem (number theory)
Ramanujan-Skolem's theorem (Diophantine equations)
Reflection theorem (algebraic number theory)
Ribet's theorem (elliptic curves)
Robin's theorem (number theory)
Rosser's theorem (number theory)
Siegel-Walfisz theorem (analytic number theory)
Six exponentials theorem (transcendental number theory)
Skolem-Mahler-Lech theorem (number theory)
Solutions to Pell's equation (number theory)
Sophie Germain's theorem (number theory)
Sphere packing theorems in dimensions 8 and 24 (geometry, modular forms)
Stark-Heegner theorem (number theory)
Subspace theorem (Diophantine approximation)
Sylvester's theorem (number theory)
Takagi existence theorem (number theory)
Thabit ibn Qurra's theorem (amicable numbers)
Thue's theorem (Diophantine equation)
Thue-Siegel-Roth theorem (Diophantine approximation)
Tijdeman's theorem (Diophantine equations)
Tunnell's theorem (number theory)
Turan-Kubilius theorem (number theory)
Vantieghems theorem (number theory)
Vinogradov's theorem (number theory)
Von Staudt-Clausen theorem (number theory)
Wilson's theorem (number theory)
Wolstenholme's theorem (number theory)
Zeckendorf's theorem (number theory)
Zsigmondy's theorem (number theory)

Field theory and polynomials
Abel-Ruffini theorem (theory of equations, Galois theory)
Artin-Schreier theorem (real closed fields)
Chevalley-Warning theorem (field theory)
Diller-Dress theorem (field theory)
Fundamental theorem of Galois theory (Galois theory)
Hasse-Arf theorem (local class field theory)
Hilbert's theorem 90 (number theory)
Isomorphism extension theorem (abstract algebra)
Joubert's theorem (algebra)
Lagrange's theorem (number theory)
Mason-Stothers theorem (polynomials)
Polynomial remainder theorem (polynomials)
Primitive element theorem (field theory)
Rational root theorem (algebra, polynomials)
Solutions of a general cubic equation (algebra)
Solutions of a general quartic equation (algebra)
Strassmann's theorem (field theory)
Sturm's theorem (theory of equations)
Vieta's formulas (quadratics)

Commutative algebra
Artin approximation theorem (commutative algebra)
Bezout's identity (number theory)
Chinese remainder theorem (number theory)
Cohen structure theorem (commutative algebra)
Factor theorem (polynomials)
Fundamental theorem of arithmetic (number theory)
Going-up and going-down theorems (commutative algebra)
Hilbert's basis theorem (commutative algebra, invariant theory)
Hilbert's syzygy theorem (commutative algebra)
Integral root theorem (algebra, polynomials)
Krull's principal ideal theorem (commutative algebra)
Lasker-Noether theorem (commutative algebra)
Linear congruence theorem (number theory, modular arithmetic)
Quillen-Suslin theorem (abstract algebra)
Redei's theorem (group theory)
Schwartz-Zippel theorem (polynomials)
Structure theorem for finitely generated modules over a principal ideal domain (abstract algebra)
Unmixedness theorem (algebraic geometry)

Algebraic geometry
AF+BG theorem (algebraic geometry)
Abel-Jacobi theorem (algebraic geometry)
Abhyankar-Moh theorem (algebraic geometry)
Addition theorem (algebraic geometry)
Andreotti-Frankel theorem (algebraic geometry)
Arithmetic Riemann-Roch theorem (algebraic geometry)
BBD decomposition theorem (algebraic geometry)
Base change theorems (algebraic geometry)
Beauville-Laszlo theorem (vector bundles)
Belyi's theorem (algebraic geometry)
Bertini's theorem (algebraic geometry)
Bezout's theorem (algebraic geometry)
Borel fixed-point theorem (algebraic geometry)
Castelnuovo theorem (algebraic geometry)
Cayley-Salmon theorem (algebraic surfaces)
Chasles' theorem (algebraic geometry)
Chevalley's structure theorem (algebraic geometry)
Faltings's theorem (Diophantine geometry)
Fulton-Hansen connectedness theorem (algebraic geometry)
Grauert-Riemenschneider vanishing theorem (algebraic geometry)
Grothendieck-Hirzebruch-Riemann-Roch theorem (algebraic geometry)
Grothendieck's connectedness theorem (algebraic geometry)
Haboush's theorem (algebraic groups, representation theory, invariant theory)
Harnack's curve theorem (real algebraic geometry)
Hasse's theorem on elliptic curves (number theory)
Hilbert's Nullstellensatz (commutative algebra, algebraic geometry)
Hironaka theorem (algebraic geometry)
Hodge index theorem (algebraic surfaces)
Katz-Lang finiteness theorem (number theory)
Lefschetz hyperplane theorem (algebraic topology)
Leray's theorem (algebraic geometry)
Manin-Drinfeld theorem (number theory)
Max Noether's theorem (algebraic geometry)
Mazur's torsion theorem (algebraic geometry)
Mumford vanishing theorem (algebraic geometry)
Nagata's compactification theorem (algebraic geometry)
Noether's theorem on rationality for surfaces (algebraic surfaces)
Proper base change theorem (algebraic geometry)
Puiseux's theorem (algebraic geometry)
Ramanujam vanishing theorem (algebraic geometry)
Reider's theorem (algebraic surfaces)
Riemann-Roch theorem for surfaces (algebraic surfaces)
Sylvester pentahedral theorem (invariant theory)
Theorem of the cube (algebraic varieties)
Torelli theorem (algebraic geometry)
Tsen's theorem (algebraic geometry)
Weber's theorem (algebraic curves)
Zariski's connectedness theorem (algebraic geometry)
Zariski's main theorem (algebraic geometry)

Linear and multilinear algebra; matrix theory
Amitsur-Levitzki theorem (linear algebra)
Binomial inverse theorem (linear algebra)
Birkhoff-Von Neumann theorem (linear algebra)
Bregman-Minc inequality (discrete mathematics)
Cauchy-Binet formula (linear algebra)
Cayley-Hamilton theorem (linear algebra)
Dimension theorem for vector spaces (vector spaces, linear algebra)
Euler's rotation theorem (geometry)
Exchange theorem (linear algebra)
Gamas's Theorem (multilinear algebra)
Gershgorin circle theorem (matrix theory)
Inverse eigenvalues theorem (linear algebra)
Perron-Frobenius theorem (matrix theory)
Principal axis theorem (linear algebra)
Rank-nullity theorem (linear algebra)
Rouche-Capelli theorem (linear algebra)
Sinkhorn's theorem (matrix theory)
Specht's theorem (matrix theory)
Spectral theorem (linear algebra, functional analysis)
Sylvester's determinant theorem (determinants)
Sylvester's law of inertia (quadratic forms)
Witt's theorem (quadratic forms)

Associative rings and algebras
Artin-Wedderburn theorem (abstract algebra)
Artin-Zorn theorem (algebra)
Brauer-Cartan-Hua theorem (ring theory)
Frobenius theorem (abstract algebras)
Goldie's theorem (ring theory)
Jacobson density theorem (ring theory)
Jacobson-Bourbaki theorem (algebra)
Levitzky's theorem (ring theory)
Regev's theorem (ring theory)
Skolem-Noether theorem (simple algebras)
Wedderburn's little theorem (ring theory)
Wedderburn's theorem (abstract algebra)

Nonassociative rings and algebras
Ado's theorem (Lie algebra)
Goddard-Thorn theorem (vertex algebras)
Hurwitz's theorem (normed division algebras)
Jacobson-Morozov theorem (Lie algebra)
Levi's theorem (Lie groups)
Lie's theorem (Lie algebra)
Poincare-Birkhoff-Witt theorem (universal enveloping algebras)
Shirshov-Cohn theorem (Jordan algebras)
Shirshov-Witt theorem (Lie algebras)

Category theory and homological algebra
Beck's monadicity theorem (category theory)
Bruguieres modularity theorem (category theory)
Freyd's adjoint functor theorem (category theory)
Golod-Shafarevich theorem (group theory)
Lawvere's fixed-point theorem (mathematical logic)
Mitchell's embedding theorem (category theory)
The duality theorem (topology)
Yoneda lemma (category theory)

K-theory
Atiyah-Segal completion theorem (homotopy theory)
Snaith's theorem (algebraic topology)

Group theory and generalizations
Alperin-Brauer-Gorenstein theorem (finite groups)
Bass-Guirvarc'h formula (group theory)
Bass-Serre theorem (group theory)
Borel-Bott-Weil theorem (representation theory)
Borel-Weil theorem (representation theory)
Brauer-Nesbitt theorem (representation theory of finite groups)
Brauer-Suzuki theorem (finite groups)
Brauer-Suzuki-Wall theorem (group theory)
Brauer's theorem (number theory)
Brauer's theorem on induced characters (representation theory of finite groups)
Burnside's theorem (group theory)
Cartan-Dieudonne theorem (group theory)
Cauchy's theorem (finite groups)
Cayley's theorem (group theory)
Chevalley-Shephard-Todd theorem (finite group)
Classification of finite simple groups (group theory)
Feit-Thompson theorem (finite groups)
Fitting's theorem (group theory)
Flat torus theorem (geometric group theory)
Focal subgroup theorem (abstract algebra)
Frobenius determinant theorem (group theory)
Frobenius reciprocity theorem (group representations)
Frucht's theorem (graph theory)
Great orthogonality theorem (group theory)
Gromov's theorem on groups of polynomial growth (geometric group theory)
Grushko theorem (group theory)
Higman's embedding theorem (group theory)
Isoperimetric gap (geometric group theory, metric geometry)
Jordan-Holder theorem (group theory)
Jordan-Schur theorem (group theory)
Jordan's theorem (multiply transitive groups) (group theory)
Krull-Schmidt theorem (group theory)
Kurosh subgroup theorem (group theory)
L-balance theorem (finite groups)
Lagrange's theorem (group theory)
Lie-Kolchin theorem (algebraic groups, representation theory)
Maschke's theorem (group representations)
Moufang's theorem (loop theory)
Nagao's theorem (group theory)
Nielsen-Schreier theorem (free groups)
Orbit-stabilizer theorem (group theory)
Schreier refinement theorem (group theory)
Schur's lemma (representation theory)
Schur-Zassenhaus theorem (group theory)
Sela's theorem (hyperbolic groups)
Stallings theorem about ends of groups (group theory)
Superrigidity theorem (algebraic groups)
Svarc-Milnor lemma (geometric group theory)
Sylow theorems (group theory)
Thompson transitivity theorem (finite groups)
Thompson uniqueness theorem (finite groups)
Tits alternative (geometric group theory)
Trichotomy theorem (finite groups)
Walter theorem (finite groups)
Z* theorem (finite groups)
ZJ theorem (finite groups)

Topological groups, Lie groups
Cartan's theorem (Lie group)
Harish-Chandra theorem (representation theory)
Harish-Chandra's regularity theorem (representation theory)
Iwasawa decomposition (Lie theory)
Kempf-Ness theorem (algebraic geometry)
Lie's third theorem (Lie group)
Montgomery-Zippin-Gleason theorem (transformation groups)
Plancherel theorem for spherical functions (representation theory)
Trombi-Varadarajan theorem (Lie group)

Real functions
Anderson's theorem (real analysis)
Bernstein's theorem (functional analysis)
Bohr-Mollerup theorem (gamma function)
Bolzano's theorem (real analysis, calculus)
Constant rank theorem (multivariate calculus)
Cousin's lemma (real analysis)
Danskin's theorem (convex analysis)
Darboux's theorem (real analysis)
Denjoy-Carleman theorem (functional analysis)
Denjoy-Young-Saks theorem (real analysis)
Dini's theorem (analysis)
Divergence theorem (vector calculus)
Fermat's theorem (stationary points) (real analysis)
Frankova-Helly selection theorem (mathematical analysis)
Froda's theorem (mathematical analysis)
Fubini's theorem on differentiation (real analysis)
Fundamental theorem of calculus (calculus)
Gauss theorem (vector calculus)
Gradient theorem (vector calculus)
Green's theorem (vector calculus)
Helly's selection theorem (mathematical analysis)
Implicit function theorem (vector calculus)
Increment theorem (mathematical analysis)
Intermediate value theorem (calculus)
Inverse function theorem (vector calculus)
Kolmogorov-Arnold representation theorem (real analysis, approximation theory)
Lebesgue differentiation theorem (real analysis)
Luzin's theorem (real analysis)
Malgrange preparation theorem (singularity theory)
Mean value theorem (calculus)
Monotone convergence theorem (mathematical analysis)
Muntz-Szasz theorem (functional analysis)
Rademacher's theorem (mathematical analysis)
Rising sun lemma (real analysis)
Rolle's theorem (calculus)
Squeeze theorem (mathematical analysis)
Stokes's theorem (vector calculus, differential topology)
Titchmarsh convolution theorem (complex analysis)
Whitney extension theorem (mathematical analysis)
Zahorski theorem (real analysis)

Measure and integration
Banach-Tarski theorem (measure theory)
Brunn-Minkowski theorem (Riemannian geometry)
Cameron-Martin theorem (measure theory)
Caratheodory's extension theorem (measure theory)
Cramer-Wold theorem (measure theory)
Disintegration theorem (measure theory)
Dominated convergence theorem (Lebesgue integration)
Egorov's theorem (measure theory)
Fatou-Lebesgue theorem (real analysis)
Fubini's theorem (integration)
Hahn decomposition theorem (measure theory)
Hahn-Kolmogorov theorem (measure theory)
Ham sandwich theorem (topology)
Hobby-Rice theorem (mathematical analysis)
Komura's theorem (measure theory)
Lebesgue's decomposition theorem (measure theory)
Lebesgue's density theorem (measure theory)
Maharam's theorem (measure theory)
Minlos's theorem (functional analysis)
Monotone class theorem (measure theory)
Prokhorov's theorem (measure theory)
Radon-Nikodym theorem (measure theory)
Schilder's theorem (stochastic processes)
Schroder-Bernstein theorem for measurable spaces (measure theory)
Stein-Stromberg theorem (measure theory)
Steinhaus theorem (measure theory)
Stone-Tukey theorem (topology)
Structure theorem for Gaussian measures (measure theory)
Vitali convergence theorem (measure theory)
Vitali theorem (measure theory)
Vitali-Hahn-Saks theorem (measure theory)

Functions of a complex variable
Akhiezer's theorem (complex analysis)
Arakelyan's theorem (complex analysis)
Area theorem (conformal mapping) (complex analysis)
Beurling-Lax theorem (Hardy spaces)
Bloch's theorem (complex analysis)
Bocher's theorem (complex analysis)
Borel-Caratheodory theorem (complex analysis)
Branching theorem (complex manifold)
Caratheodory's theorem (complex analysis)
Carleson-Jacobs theorem (complex analysis)
Carlson's theorem (complex analysis)
Cauchy integral theorem (complex analysis)
Cauchy-Hadamard theorem (complex analysis)
Clifford's theorem on special divisors (algebraic curves)
Corona theorem (complex analysis)
de Branges's theorem (complex analysis)
De Franchis theorem (Riemann surfaces)
Edge-of-the-wedge theorem (complex analysis)
Farrell-Markushevich theorem (complex analysis)
Fatou's theorem (complex analysis)
Fundamental theorem of algebra (complex analysis)
Gauss-Lucas theorem (complex analysis)
Grunsky's theorem (complex analysis)
Hadamard three-circle theorem (complex analysis)
Hadamard three-lines theorem (complex analysis)
Hardy's theorem (complex analysis)
Hartogs-Rosenthal theorem (complex analysis)
Harnack's theorem (complex analysis)
Hurwitz's automorphisms theorem (algebraic curves)
Hurwitz's theorem (complex analysis)
Identity theorem (complex analysis)
Identity theorem for Riemann surfaces (Riemann surfaces)
Koebe 1/4 theorem (complex analysis)
Lagrange inversion theorem (mathematical analysis, combinatorics)
Lagrange reversion theorem (mathematical analysis, combinatorics)
Laurent expansion theorem (complex analysis)
Lindelof's theorem (complex analysis)
Liouville's theorem (complex analysis, entire functions)
Liouville's theorem (conformal mappings)
Looman-Menchoff theorem (complex analysis)
Marden's theorem (polynomials)
Mergelyan's theorem (complex analysis)
Measurable Riemann mapping theorem (conformal mapping)
Mittag-Leffler's theorem (complex analysis)
Monodromy theorem (complex analysis)
Montel's theorem (complex analysis)
Morera's theorem (complex analysis)
Nachbin's theorem (complex analysis)
Open mapping theorem (complex analysis)
Ostrowski-Hadamard gap theorem (complex analysis)
Phragmen-Lindelof theorem (complex analysis)
Picard theorem (complex analysis)
Residue theorem (complex analysis)
Riemann mapping theorem (complex analysis)
Riemann's existence theorem (algebraic geometry)
Riemann's theorem on removable singularities (complex analysis)
Riemann-Roch theorem (Riemann surfaces, algebraic curves)
Rouche's theorem (complex analysis)
Routh-Hurwitz theorem (polynomials)
Runge's theorem (complex analysis)
Siu's semicontinuity theorem (complex analysis)
Sokhatsky-Weierstrass theorem (complex analysis)
Uniformization theorem (complex analysis, differential geometry)
Van Vleck's theorem (mathematical analysis)
Weierstrass-Casorati theorem (complex analysis)
Weierstrass factorization theorem (complex analysis)

Several complex variables and analytic spaces
Appell-Humbert theorem (complex manifold)
Baily-Borel theorem (algebraic geometry)
Behnke-Stein theorem (several complex variables)
Birkhoff-Grothendieck theorem (complex geometry)
Bochner's tube theorem (complex analysis)
Cartan's theorems A and B (several complex variables)
Castelnuovo-de Franchis theorem (algebraic geometry)
Chow's theorem (algebraic geometry)
Cramer's theorem (algebraic curves) (analytic geometry)
Hartogs's theorem (complex analysis)
Hartogs's extension theorem (several complex variables)
Hirzebruch-Riemann-Roch theorem (complex manifolds)
Kawamata-Viehweg vanishing theorem (algebraic geometry)
Kodaira embedding theorem (algebraic geometry)
Kodaira vanishing theorem (complex manifold)
Lefschetz theorem on (1,1)-classes (algebraic geometry)
Local invariant cycle theorem (algebraic geometry)
Malgrange-Zerner theorem (complex analysis)
Newlander-Niremberg theorem (differential geometry)
Remmert-Stein theorem (complex analysis)
Riemann singularity theorem (algebraic geometry)
Skoda-El Mir theorem (complex geometry)
Weierstrass preparation theorem (several complex variables, commutative algebra)

Special functions
De Moivre's theorem (complex analysis)
Holder's theorem (mathematical analysis)
Multiplication theorem (special functions)

Ordinary differential equations
Caratheodory's existence theorem (ordinary differential equations)
Floquet's theorem (differential equations)
Fuchs's theorem (differential equations)
Kharitonov's theorem (control theory)
Kneser's theorem (differential equations)
Lienard's theorem (dynamical systems)
Markus-Yamabe theorem (dynamical systems)
Peano existence theorem (ordinary differential equations)
Picard-Lindelof theorem (ordinary differential equations)
Shift theorem (differential operators)
Sturm-Picone comparison theorem (differential equations)

Partial differential equations
Cartan-Kahler theorem (partial differential equations)
Cartan-Kuranishi prolongation theorem (partial differential equations)
Cauchy-Kowalevski theorem (partial differential equations)
Malgrange-Ehrenpreis theorem (differential equations)

Dynamical systems and ergodic theory
Autonomous convergence theorem (dynamical systems)
Banach fixed-point theorem (metric spaces, differential equations)
Bendixson-Dulac theorem (dynamical systems)
Birkhoff's theorem (ergodic theory)
Conley-Zehnder theorem (dynamical systems)
Curtis-Hedlund-Lyndon theorem (cellular automata)
Hartman-Grobman theorem (dynamical systems)
Kolmogorov-Arnold-Moser theorem (dynamical systems)
Krylov-Bogolyubov theorem (dynamical systems)
Maximal ergodic theorem (ergodic theory)
No wandering domain theorem (ergodic theory)
Noether's theorem (Lie groups, calculus of variations, differential invariants, physics)
Ornstein theorem (ergodic theory)
Oseledec theorem (ergodic theory)
Peixoto's theorem (dynamical systems)
Poincare-Bendixson theorem (dynamical systems)
Poincare recurrence theorem (dynamical systems)
Ratner's theorems (ergodic theory)
Sarkovskii's theorem (dynamical systems)
Takens's theorem (dynamical systems)

Difference and functional equations
Euler's theorem on homogeneous functions (multivariate calculus)

Sequence, series, summability
Abel's theorem (mathematical analysis)
Abelian and Tauberian theorems (mathematical analysis)
Absolute convergence theorem (mathematical series)
Cesaro's theorem (real analysis)
Hardy-Littlewood tauberian theorem (mathematical analysis)
Riemann series theorem (mathematical series)
Silverman-Toeplitz theorem (mathematical analysis)
Sleszynski-Pringsheim theorem (continued fraction)
Stolz-Cesaro theorem (calculus)

Approximations and expansions
Stone-Weierstrass theorem (functional analysis)
Taylor's theorem (calculus)

Harmonic analysis on Euclidean spaces
Balian-Low theorem (Fourier analysis)
Bernstein's theorem (approximation theory)
Carleson's theorem (harmonic analysis)
Convolution theorem (Fourier transforms)
Denjoy theorem (dynamical systems)
Fourier inversion theorem (harmonic analysis)
Fourier theorem (harmonic analysis)
Hausdorff-Young inequality (Fourier analysis)
Lauricella's theorem (functional analysis)
Paley-Wiener theorem (Fourier transforms)
Parseval's theorem (Fourier analysis)
Plancherel theorem (Fourier analysis)
Riesz-Fischer theorem (real analysis)
Szego limit theorems (mathematical analysis)
Wiener's tauberian theorem (real analysis)
Wiener-Ikehara theorem (number theory)

Abstract harmonic analysis
F. and M. Riesz theorem (measure theory)
Peter-Weyl theorem (representation theory)
Pontryagin duality theorem (representation theory)

Integral transforms, operational calculus
Final value theorem (mathematical analysis)
Initial value theorem (integral transform)
Mellin inversion theorem (complex analysis)
Stahl's theorem (matrix analysis)
Titchmarsh theorem (integral transform)

Integral equations
Fredholm's theorem (linear algebra)

Functional analysis
Analytic Fredholm theorem (functional analysis)
Banach-Alaoglu theorem (functional analysis)
Banach-Mazur theorem (functional analysis)
Banach-Steinhaus theorem (functional analysis)
Choquet-Bishop-de Leeuw theorem (functional analysis)
Closed range theorem (functional analysis)
Dunford-Schwartz theorem (functional analysis)
Eberlein-Smulian theorem (functional analysis)
Goldstine theorem (functional analysis)
Hahn-Banach theorem (functional analysis)
Hilbert projection theorem (convex analysis)
Kachurovskii's theorem (convex analysis)
Kirszbraun theorem (Lipschitz continuity)
M. Riesz extension theorem (functional analysis)
Milman-Pettis theorem (Banach space)
Moore-Aronszajn theorem (Hilbert space)
Orlicz-Pettis theorem (functional analysis)
Quotient of subspace theorem (functional analysis)
Riesz representation theorem (functional analysis, Hilbert space)
Schauder fixed-point theorem (functional analysis)
Schwartz kernel theorem (generalized functions)
Sobczyk's theorem (functional analysis)
Sobolev embedding theorem (mathematical analysis)
Soler's theorem (mathematical logic)
Tikhonov fixed-point theorem (functional analysis)
Trudinger's theorem (functional analysis)

Operator theory
Aronszajn-Smith theorem (functional analysis)
Atiyah-Singer index theorem (elliptic differential operators, harmonic analysis)
Atkinson's theorem (operator theory)
Babuska-Lax-Milgram theorem (partial differential equations)
Banach-Stone theorem (operator theory)
Bauer-Fike theorem (spectral theory)
Bounded inverse theorem (operator theory)
Browder-Minty theorem (operator theory)
Choi's theorem on completely positive maps (operator theory)
Commutation theorem (von Neumann algebra)
Fuglede's theorem (functional analysis)
Gelfand-Mazur theorem (Banach algebra)
Gelfand-Naimark theorem (functional analysis)
Hardy-Littlewood maximal theorem (real analysis)
Hellinger-Toeplitz theorem (functional analysis)
Hilbert-Schmidt theorem (functional analysis)
Hille-Yosida theorem (functional analysis)
Kaplansky density theorem (von Neumann algebra)
Kuiper's theorem (operator theory, topology)
Lax-Milgram theorem (partial differential equations)
Lions-Lax-Milgram theorem (partial differential equations)
Lumer-Phillips theorem (semigroup theory)
Marcinkiewicz theorem (functional analysis)
Mazur-Ulam theorem (normed spaces)
Mercer's theorem (functional analysis)
Min-max theorem (functional analysis)
Moreau's theorem (convex analysis)
Nash-Moser theorem (mathematical analysis)
Open mapping theorem (functional analysis)
Peetre theorem (functional analysis)
Riesz-Thorin theorem (functional analysis)
Ryll-Nardzewski fixed-point theorem (functional analysis)
Sazonov's theorem (functional analysis)
Schroder-Bernstein theorems for operator algebras (operator algebras)
Stinespring factorization theorem (operator theory)
Stone's theorem on one-parameter unitary groups (functional analysis)
Sz.-Nagy's dilation theorem (operator theory)
Tomita's theorem (operator algebras)
Von Neumann bicommutant theorem (functional analysis)
Von Neumann's theorem (operator theory)

Calculus of variations and optimal control; optimization
Caristi fixed-point theorem (fixed points)
Envelope theorem (calculus of variations)
Isoperimetric theorem (curves, calculus of variations)
Minimax theorem (game theory)
Mountain pass theorem (calculus of variations)
Noether's second theorem (calculus of variations, physics)
Parthasarathy's theorem (game theory)
Sion's minimax theorem (game theory)
Tonelli's theorem (functional analysis)

Geometry
Alternate Interior Angles Theorem (geometry)
Alternate segment theorem (geometry)
Angle bisector theorem (Euclidean geometry)
Anne's theorem (geometry)
Apollonius's theorem (plane geometry)
Barbier's theorem (geometry)
Beck's theorem (incidence geometry)
Beckman-Quarles theorem (Euclidean geometry)
Beer's theorem (metric geometry)
Brahmagupta theorem (Euclidean geometry)
Brianchon's theorem (conics)
British flag theorem (Euclidean geometry)
Butterfly theorem (Euclidean geometry)
CPCTC (triangle geometry)
Carnot's theorem (geometry)
Casey's theorem (Euclidean geometry)
Cayley-Bacharach theorem (projective geometry)
Ceva's theorem (geometry)
Clifford's circle theorems (Euclidean plane geometry)
Commandino's theorem (geometry)
Constant chord theorem (geometry)
Conway circle theorem (Euclidean plane geometry)
Crossbar theorem (Euclidean plane geometry)
Dandelin's theorem (solid geometry)
De Bruijn-Erdos theorem (incidence geometry)
De Gua's theorem (geometry)
Desargues's theorem (projective geometry)
Descartes's theorem (plane geometry)
Dinostratus' theorem (geometry, analysis)
Equal incircles theorem (Euclidean geometry)
Euler's quadrilateral theorem (geometry)
Euler's theorem in geometry (triangle geometry)
Exterior angle theorem (triangle geometry)
Feuerbach's theorem (geometry)
Finsler-Hadwiger theorem (geometry)
Five circles theorem (circles)
Gauss-Wantzel theorem (geometry)
Geometric mean theorem (geometry)
Hinge theorem (geometry)
Hjelmslev's theorem (geometry)
Impossibility of angle trisection (geometry)
Independence of the parallel postulate (geometry)
Inscribed angle theorem (geometry)
Intercept theorem (Euclidean geometry)
Intersecting chords theorem (Euclidean geometry)
Intersecting secants theorem (Euclidean geometry)
Intersection theorem (projective geometry)
Japanese theorem for concyclic polygons (Euclidean geometry)
Japanese theorem for concyclic quadrilaterals (Euclidean geometry)
Kawasaki's theorem (mathematics of paper folding)
Lester's theorem (Euclidean plane geometry)
Lexell's theorem (spherical geometry)
Menelaus's theorem (geometry)
Miquel's theorem (geometry)
Mohr-Mascheroni theorem (geometry)
Monge's theorem (geometry)
Morley's trisector theorem (geometry)
Napoleon's theorem (triangle geometry)
Newton's theorem about ovals (curves)
Newton's theorem (quadrilateral) (geometry)
Pappus's area theorem (geometry)
Pappus's centroid theorem (geometry)
Pappus's hexagon theorem (geometry)
Pascal's theorem (conics)
Pasch's theorem (order theory)
Pitot theorem (plane geometry)
Pivot theorem (circles)
Pompeiu's theorem (Euclidean geometry)
Poncelet's closure theorem (conics)
Poncelet-Steiner theorem (geometry)
Ptolemy's theorem (geometry)
Pythagorean theorem (geometry)
Reuschle's theorem (Euclidean geometry)
Routh's theorem (triangle geometry)
Saccheri-Legendre theorem (absolute geometry)
Six circles theorem (circles)
Steiner-Lehmus theorem (triangle geometry)
Symphonic theorem (triangle geometry)
Tangent-secant theorem (geometry)
Thales's theorem (geometry)
Thebault's theorem (geometry)
Theorem of the gnomon (geometry)
Thomsen's theorem (geometry)
Van Aubel's theorem (quadrilaterals)
Van Schooten's theorem (Euclidean geometry)
Varignon's theorem (Euclidean geometry)
Viviani's theorem (Euclidean geometry)

Convex and discrete geometry
Alexandrov's uniqueness theorem (discrete geometry)
Balinski's theorem (combinatorics)
Bang's theorem (geometry)
Besicovitch covering theorem (mathematical analysis)
Blaschke selection theorem (geometric topology)
Bolyai-Gerwien theorem (discrete geometry)
Busemann's theorem (Euclidean geometry)
Caratheodory's theorem (convex geometry)
Cauchy's theorem (geometry)
Classification of Platonic solids (geometry)
de Bruijn's theorem (discrete geometry)
Descartes's theorem on total angular defect (polyhedra)
Erdos-Anning theorem (discrete geometry)
Erdos-Nagy theorem (discrete geometry)
Erdos-Szekeres theorem (discrete geometry)
Fary's theorem (graph theory)
Fenchel's duality theorem (convex analysis)
Fenchel-Moreau theorem (mathematical analysis)
Hadwiger's theorem (geometry, measure theory)
Helly's theorem (convex sets)
Holditch's theorem (plane geometry)
John ellipsoid (geometry)
Jung's theorem (geometry)
Kepler conjecture (discrete geometry)
Kirchberger's theorem (discrete geometry)
Krein-Milman theorem (mathematical analysis, discrete geometry)
Minkowski's theorem (geometry of numbers)
Minkowski's second theorem (geometry of numbers)
Minkowski-Hlawka theorem (geometry of numbers)
Monsky's theorem (discrete geometry)
Pick's theorem (geometry)
Pizza theorem (geometry)
Radon's theorem (convex sets)
Separating axis theorem (convex geometry)
Steinitz theorem (graph theory)
Stewart's theorem (plane geometry)
Supporting hyperplane theorem (convex geometry)
Sylvester-Gallai theorem (plane geometry)
Szemeredi-Trotter theorem (combinatorics)
Tverberg's theorem (discrete geometry)
Vitali covering theorem (measure theory)
Wallace-Bolyai-Gerwien theorem (discrete geometry)

Differential geometry
2-pi theorem (Riemannian geometry)
Abel's curve theorem (Riemannian geometry)
Beltrami's theorem (Riemannian geometry)
Berger-Kazdan comparison theorem (Riemannian geometry)
Bertrand-Diquet-Puiseux theorem (differential geometry)
Bishop-Gromov inequality (Riemannian geometry)
Bonnet theorem (differential geometry)
Caratheodory-Jacobi-Lie theorem (symplectic topology)
Cartan-Hadamard theorem (Riemannian geometry)
Cheng's eigenvalue comparison theorem (Riemannian geometry)
Chern-Gauss-Bonnet theorem (differential geometry)
Classification of symmetric spaces (Lie theory)
Darboux's theorem (symplectic topology)
Euler's theorem (differential geometry)
Four-vertex theorem (differential geometry)
Frobenius theorem (foliations)
Gauss's lemma (Riemannian geometry)
Gauss's Theorema Egregium (differential geometry)
Gauss-Bonnet theorem (differential geometry)
Geroch's splitting theorem (differential geometry)
Gromov's compactness theorem (Riemannian geometry)
Gromov's compactness theorem (symplectic topology)
Gromov-Ruh theorem (differential geometry)
Hilbert's theorem (differential geometry)
Hopf-Rinow theorem (differential geometry)
Killing-Hopf theorem (Riemannian geometry)
Lee Hwa Chung theorem (symplectic topology)
Lie-Palais theorem (differential geometry)
Meusnier's theorem (differential geometry)
Mostow rigidity theorem (differential geometry)
Myers theorem (differential geometry)
Myers-Steenrod theorem (differential geometry)
Nash embedding theorem (differential geometry)
Non-squeezing theorem (symplectic geometry)
Rashevsky-Chow theorem (control theory)
Rauch comparison theorem (Riemannian geometry)
Schwarz-Ahlfors-Pick theorem (differential geometry)
Soul theorem (Riemannian geometry)
Sphere theorem (Riemannian geometry)
Synge's theorem (Riemannian geometry)
Toponogov's theorem (Riemannian geometry)

General topology
Arzela-Ascoli theorem (functional analysis)
Baire category theorem (topology, metric spaces)
Bing metrization theorem (general topology)
Bolzano-Weierstrass theorem (real analysis, calculus)
Borsuk-Ulam theorem (topology)
Brouwer fixed-point theorem (topology)
Cantor's intersection theorem (real analysis)
Closed graph theorem (functional analysis)
Extreme value theorem (calculus)
Fixed-point theorems in infinite-dimensional spaces (topology)
Hairy ball theorem (algebraic topology)
Hahn-Mazurkiewicz theorem (continuum theory)
Heine-Borel theorem (real analysis)
Heine-Cantor theorem (metric geometry)
Jordan curve theorem (topology)
Kuratowski's closure-complement problem (topology)
Lebesgue covering dimension (dimension theory)
Metrization theorems (topological spaces)
Nagata-Smirnov metrization theorem (general topology)
Netto's theorem (topology)
Parovicenko's theorem (topology)
Tietze extension theorem (general topology)
Tychonoff's theorem (general topology)

Algebraic topology
Acyclic models theorem (algebraic topology)
Blakers-Massey theorem (homotopy theory)
Bott periodicity theorem (homotopy theory)
Brown's representability theorem (homotopy theory)
Cellular approximation theorem (algebraic topology)
Dold-Thom theorem (algebraic topology)
Eilenberg-Ganea theorem (homological algebra, algebraic topology)
Eilenberg-Zilber theorem (algebraic topology)
Euler's polyhedron theorem (polyhedra)
Excision theorem (homology theory)
Freudenthal suspension theorem (homotopy theory)
Hilton-Milnor theorem (algebraic topology)
Homotopy excision theorem (algebraic topology)
Hopf theorem (differential topology)
Hurewicz theorem (algebraic topology)
Kunneth theorem (algebraic topology)
Invariance of domain (algebraic topology)
Landweber exact functor theorem (algebraic topology)
Lefschetz fixed-point theorem (fixed points, algebraic topology)
Lefschetz-Hopf theorem (topology)
Leray-Hirsch theorem (algebraic topology)
Nielsen fixed-point theorem (fixed points)
Nilpotence theorem (algebraic topology)
Poincare duality theorem (algebraic topology of manifolds)
Seifert-van Kampen theorem (algebraic topology)
Simplicial approximation theorem (algebraic topology)
Stallings-Zeeman theorem (algebraic topology)
Sullivan conjecture (homotopy theory)
Universal coefficient theorem (algebraic topology)
Vietoris-Begle mapping theorem (algebraic topology)
Whitehead theorem (homotopy theory)
Whitney-Graustein Theorem (algebraic topology)

Manifolds and cell complexes
Atiyah-Bott fixed-point theorem (differential topology)
Bing's recognition theorem (geometric topology)
Birman short exact sequence (geometric topology)
Classification of compact surfaces (topology)
De Rham's theorem (differential topology)
Dehn-Nielsen-Baer theorem (geometric topology)
Donaldson's theorem (differential topology)
Ehresmann's theorem (differential topology)
Fary-Milnor theorem (knot theory)
Fenchel's theorem (differential geometry)
H-cobordism theorem (differential topology)
Hirzebruch signature theorem (topology, algebraic geometry)
Jordan-Schonflies theorem (geometric topology)
JSJ theorem (3-manifolds)
Lickorish twist theorem (geometric topology)
Lickorish-Wallace theorem (3-manifolds)
Nielsen realization problem (geometric topology)
Nielsen-Thurston classification (low-dimensional topology)
Novikov's compact leaf theorem (foliations)
Perelman's Geometrization theorem (3-manifolds)
Poincare-Hopf theorem (differential topology)
Poincare conjecture (topology)
Preimage theorem (differential topology)
Reeb sphere theorem (foliations)
Reidemeister-Singer Theorem (geometric topology)
Riemann-Roch theorem for smooth manifolds (differential topology)
Rokhlin's theorem (geometric topology)
S-cobordism theorem (differential topology)
Sard's theorem (differential geometry)
Scott core theorem (3-manifolds)
Swan's theorem (module theory)
Tameness theorem (3-manifolds)
Thom transversality theorem (differential topology)
Thurston's geometrization theorem (3-manifolds)
Waldhausen's theorem (geometric topology)
Whitney embedding theorem (differential manifolds)
Whitney immersion theorem (differential topology)

Global analysis, analysis on manifolds
Rado's theorem (harmonic analysis)

Probability theory and stochastic processes
Bayes' theorem (probability)
Bertrand's ballot theorem (probability theory, combinatorics)
Burke's theorem (probability theory, queueing theory)
Central limit theorem (probability)
Clark-Ocone theorem (stochastic processes)
Continuous mapping theorem (probability theory)
Cramer's theorem (large deviations) (probability)
Dawson-Gartner theorem (asymptotic analysis)
Donsker's theorem (probability theory)
Doob decomposition theorem (stochastic processes)
Doob's martingale convergence theorems (stochastic processes)
Doob-Meyer decomposition theorem (stochastic processes)
Dudley's theorem (probability)
Dunford-Pettis theorem (probability theory)
Fernique's theorem (measure theory)
Foster's theorem (statistics)
Freidlin-Wentzell theorem (stochastic processes)
Girsanov's theorem (stochastic processes)
Glivenko's theorem (probability)
Gordon-Newell theorem (queueing theory)
Hammersley-Clifford theorem (probability)
Helly-Bray theorem (probability theory)
Integral representation theorem for classical Wiener space (measure theory)
Ionescu-Tulcea theorem (probability theory)
Jackson's theorem (queueing theory)
Karhunen-Loeve theorem (stochastic processes)
Kolmogorov extension theorem (stochastic processes)
Kolmogorov's three-series theorem (mathematical series)
Le Cam's theorem (probability theory)
Levy continuity theorem (probability)
Levy's modulus of continuity theorem (probability)
Martingale representation theorem (probability theory)
Maxwell's theorem (probability theory)
Optional stopping theorem (probability theory)
Poisson limit theorem (probability)
Raikov's theorem (probability)
Skorokhod's embedding theorem (statistics)
Skorokhod's representation theorem (statistics)
Slutsky's theorem (probability theory)
Theorem of de Moivre-Laplace (probability theory)

Statistics
Aumann's agreement theorem (statistics)
Bapat-Beg theorem (statistics)
Basu's theorem (statistics)
Berry-Esseen theorem (probability theory)
Cochran's theorem (statistics)
Cox's theorem (probability)
Cramer's decomposition theorem (statistics)
De Finetti's theorem (probability)
FWL theorem (economics)
Fieller's theorem (statistics)
Fisher-Tippett-Gnedenko theorem (statistics)
Gauss-Markov theorem (statistics)
Glivenko-Cantelli theorem (probability)
Infinite monkey theorem (probability)
Lehmann-Scheffe theorem (statistics)
Lukacs's proportion-sum independence theorem (probability)
Lyapunov's central limit theorem (probability theory)
Pickands-Balkema-de Haan theorem (extreme value theory)
Pitman-Koopman-Darmois theorem (statistics)
Rao-Blackwell theorem (statistics)
Sklar's theorem (statistics)
Wold's theorem (statistics)

Numerical analysis
Godunov's theorem (numerical analysis)
Kantorovich theorem (functional analysis)
Lax-Richtmyer theorem (numerical analysis)
Lax-Wendroff theorem (numerical analysis)
Marsaglia's theorem (number theory)

Computer science
Akra-Bazzi theorem (computer science)
Art gallery theorem (geometry)
CAP theorem (theoretical computer science)
Chomsky-Schutzenberger enumeration theorem (formal language theory)
Chomsky-Schutzenberger representation theorem (formal language theory)
Codd's theorem (relational model)
Compression theorem (computational complexity theory, structural complexity theory)
Cook's theorem (computational complexity theory)
Fagin's theorem (computational complexity theory)
Full employment theorem (theoretical computer science)
Gap theorem (computational complexity theory)
Gottesman-Knill theorem (quantum computation)
Holland's schema theorem (genetic algorithm)
Immerman-Szelepcsenyi theorem (computational complexity theory)
Karp-Lipton theorem (computational complexity theory)
Ladner's theorem (computational complexity theory)
Lame's theorem (computational complexity theory)
Linear speedup theorem (computational complexity theory)
Master theorem (analysis of algorithms) (recurrence relations, asymptotic analysis)
Max/min CSP/Ones classification theorems (computational complexity theory)
Myhill-Nerode theorem (formal languages)
No free lunch theorem (search and optimization) (computational complexity theory)
PCP theorem (computational complexity theory)
Pseudorandom generator theorem (computational complexity theory)
Quantum threshold theorem (computer science) (theoretical computer science)
Reversed compound agent theorem (probability)
Rice's theorem (recursion theory, computer science)
Rice-Shapiro theorem (computer science)
Savitch's theorem (computational complexity theory)
Schaefer's dichotomy theorem (computational complexity theory)
Sipser-Lautemann theorem (probabilistic complexity theory) (structural complexity theory)
Smn theorem (recursion theory, computer science)
Space hierarchy theorem (computational complexity theory)
Speedup theorem (computational complexity theory)
Structured program theorem (computer science)
Time hierarchy theorem (computational complexity theory)
Toda's theorem (computational complexity theory)
Universal approximation theorem (artificial neural networks)
Valiant-Vazirani theorem (computational complexity theory)

Mechanics of particles and systems
Chasles' theorem (kinematics)
Chasles' theorem (gravity)
Helmholtz theorem (classical mechanics) (physics)
Konig's theorem (physics)
Lami's theorem (statics)
Liouville's theorem (Hamiltonian mechanics)
Parallel axis theorem (physics)
Perpendicular axis theorem (physics)
Virial theorem (classical mechanics)

Mechanics of deformable solids
Betti's theorem (physics)
Castigliano's first and second theorems (structural analysis)
Clapeyron's theorem (physics)
Saint-Venant's theorem (physics)
Theorem of three moments (physics)

Fluid mechanics
Buckingham pi theorem (dimensional analysis)
Helmholtz's theorems (physics)
Kelvin's circulation theorem (physics)
Kutta-Joukowski theorem (physics)
Reynolds transport theorem (fluid dynamics)
Taylor-Proudman theorem (physics)

Optics, electromagnetic theory
Blondel's theorem (electric power) (physics)
Earnshaw's theorem (electrostatics)
Maximum power theorem (electrical circuits)
Norton's theorem (electrical networks)
Optical theorem (physics)
Poynting's theorem (physics)
Thevenin's theorem (electrical circuits)

Classical thermodynamics, heat transfer
Carnot's theorem (thermodynamics)
Clausius theorem (physics)

Quantum theory
Adiabatic theorem (physics)
Bell's theorem (quantum mechanics)
Bogoliubov-Parasyuk theorem (quantum field theory)
Byers-Yang theorem (quantum mechanics)
C-theorem (physics)
Cluster decomposition theorem (quantum field theory)
Coleman-Mandula theorem (quantum field theory)
Elitzur's theorem (quantum field theory, statistical field theory)
Furry's theorem (quantum field theory)
Gell-Mann and Low theorem (quantum field theory)
Gleason's theorem (Hilbert space)
Goldstone's theorem (physics)
Haag's theorem (quantum field theory)
Haag-Lopuszanski-Sohnius theorem (physics)
Hellmann-Feynman theorem (physics)
Kinoshita-Lee-Nauenberg theorem (quantum field theory)
Kochen-Specker theorem (physics)
Kramers' theorem (physics)
Nielsen-Ninomiya theorem (quantum field theory)
No-broadcasting theorem (quantum information theory)
No-cloning theorem (quantum computation)
No-communication theorem (quantum information theory)
No-deleting theorem (quantum information theory)
Optical equivalence theorem (quantum optics)
Osterwalder-Schrader theorem (physics)
Pandya theorem (nuclear physics)
Pomeranchuk's theorem (physics)
Reeh-Schlieder theorem (local quantum field theory)
Solovay-Kitaev theorem (quantum computation)
Spin-statistics theorem (physics)
Stone-von Neumann theorem (functional analysis, representation theory of the Heisenberg group, quantum mechanics)
Supersymmetry nonrenormalization theorems (physics)
Vafa-Witten theorem (physics)
Weinberg-Witten theorem (quantum field theory)
Wick's theorem (physics)
Wigner-Eckart theorem (Clebsch-Gordan coefficients)

Statistical mechanics, structure of matter
Bohr-van Leeuwen theorem (physics)
Crooks fluctuation theorem (physics)
Crystallographic restriction theorem (group theory, crystallography)
Equipartition theorem (ergodic theory)
Fluctuation dissipation theorem (physics)
Fluctuation theorem (statistical mechanics)
H-theorem (thermodynamics)
Hohenberg-Kohn theorems (density functional theory)
Lee-Yang theorem (statistical mechanics)
Mermin-Wagner theorem (physics)

Relativity and gravitational theory
Birkhoff's theorem (general relativity)
Goldberg-Sachs theorem (physics)
Lovelock's theorem (physics)
No-hair theorem (physics)
Odd number theorem (physics)
Peeling theorem (physics)
Penrose-Hawking singularity theorems (physics)
Positive energy theorem (physics)
Price's theorem (general relativity)

Astronomy and astrophysics
Clairaut's theorem (physics)
Shell theorem (physics)

Operations research, mathematical programming
Analyst's traveling salesman theorem (discrete mathematics)
Arrival theorem (queueing theory)
Blum's speedup theorem (computational complexity theory)
Max flow min cut theorem (graph theory)
No free lunch theorem (philosophy of mathematics)
Topkis's theorem (economics)

Game theory, economics, social and behavioral sciences
Alchian-Allen theorem (economics)
Arrow's impossibility theorem (game theory)
Arrow-Lind theorem (welfare economics)
Bishop-Cannings theorem (economics)
Bondareva-Shapley theorem (economics)
Coase theorem (economics)
Duggan-Schwartz theorem (voting theory)
Edgeworth's limit theorem (economics)
Faustman-Ohlin theorem (economics)
Fisher separation theorem (economics)
Folk theorem (game theory)
Fundamental theorem of arbitrage-free pricing (financial mathematics)
Fundamental theorems of welfare economics (economics)
Gibbard-Satterthwaite theorem (voting methods)
Heckscher-Ohlin theorem (economics)
Holmstrom's theorem (economics)
Kuhn's theorem (game theory)
Lerner symmetry theorem (economics)
May's theorem (game theory)
Modigliani-Miller theorem (finance theory)
Morton's theorem (game theory)
Moving equilibrium theorem (economics)
Mutual fund separation theorem (financial mathematics)
No-trade theorem (economics)
Rationality theorem (politics)
Rybczynski theorem (economics)
Sonnenschein-Mantel-Debreu Theorem (economics)
Sprague-Grundy theorem (combinatorial game theory)
Stolper-Samuelson theorem (economics)

Biology and other natural sciences
Marginal value theorem (biology, optimization)

Systems theory; control
Artstein's theorem (control theory)
Krener's theorem (control theory)
Lyapunov-Malkin theorem (stability theory)
Orbit theorem (Nagano-Sussmann) (control theory)

Information and communication, circuits
Kraft-McMillan theorem (coding theory)
Nyquist-Shannon sampling theorem (information theory)
Shannon-Hartley theorem (information theory)
Shannon's source coding theorem (information theory)
Shannon's theorem (information theory)
Ugly duckling theorem (computer science)
"""


def setup_kb():
    pass


def parse_theorems(raw: str) -> dict:
    """Parse raw theorem text into {category: [{name, fields, slug}, ...]}."""
    categories = {}
    current_cat = "Uncategorized"

    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue

        m = THEOREM_RE.match(line)
        if m:
            fields = [f.strip() for f in m.group("fields").split(",")]
            entry = {
                "name": m.group("name").strip(),
                "fields": fields,
                "slug": re.sub(
                    r"[^a-z0-9]+", "_", m.group("name").strip().lower()
                ).strip("_"),
            }
            categories.setdefault(current_cat, []).append(entry)
        else:
            # Category header (no parentheses)
            if "(" not in line:
                current_cat = line
            else:
                categories.setdefault(current_cat, []).append(
                    {
                        "name": line,
                        "fields": [],
                        "slug": re.sub(r"[^a-z0-9]+", "_", line.lower()).strip("_"),
                    }
                )

    return categories


def write_category_file(cat_dir: Path, cat_name: str, theorems: list) -> Path:
    """Write a per-category markdown index."""
    slug = re.sub(r"[^a-z0-9]+", "_", cat_name.lower()).strip("_")
    path = cat_dir / f"{slug}.md"
    lines = [f"# {cat_name}", "", f"**{len(theorems)} theorems**", ""]
    for t in sorted(theorems, key=lambda x: x["name"].lower()):
        field_str = ", ".join(t["fields"]) if t["fields"] else ""
        if field_str:
            lines.append(f"- **{t['name']}** -- {field_str}")
        else:
            lines.append(f"- **{t['name']}**")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main():
    print("=" * 56)
    print("  SWARMZ Theorem Knowledge Base -- Setup")
    print("=" * 56)
    print()

    # 1. Create folder structure
    KB_DIR.mkdir(exist_ok=True)
    CATEGORIES_DIR.mkdir(exist_ok=True)
    print(f"  [1/5] Created folder: {KB_DIR.relative_to(ROOT)}/")

    # 2. Write raw theorems
    RAW_FILE.write_text(RAW_THEOREMS.strip(), encoding="utf-8")
    print(f"  [2/5] Wrote raw_theorems.txt ({len(RAW_THEOREMS.strip()):,} chars)")

    # 3. Parse
    categories = parse_theorems(RAW_THEOREMS)
    total = sum(len(v) for v in categories.values())
    print(f"  [3/5] Parsed {total} theorems across {len(categories)} categories")

    # 4. Write structured JSON
    PARSED_FILE.write_text(
        json.dumps(categories, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print("  [4/5] Wrote theorems.json")

    # 5. Write per-category markdown + index
    cat_files = []
    for cat_name, theorems in sorted(categories.items()):
        p = write_category_file(CATEGORIES_DIR, cat_name, theorems)
        cat_files.append(
            {
                "category": cat_name,
                "count": len(theorems),
                "file": str(p.relative_to(ROOT)),
            }
        )

    index_data = {
        "generated": datetime.now().isoformat(),
        "total_theorems": total,
        "total_categories": len(categories),
        "categories": cat_files,
    }
    INDEX_FILE.write_text(
        json.dumps(index_data, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"  [5/5] Wrote index.json + {len(cat_files)} category files")

    # Summary
    print()
    print("  -- Summary " + "-" * 43)
    print(f"  Total theorems : {total}")
    print(f"  Categories     : {len(categories)}")
    print(f"  KB directory   : {KB_DIR}")
    print()
    for cf in cat_files:
        print(f"    {cf['count']:>4}  {cf['category']}")
    print()
    print("  Done. Theorem knowledge base ready.")


if __name__ == "__main__":
    main()
