const { normalizeId, toJson, nowIso } = require("./_shared.js");

async function generate(payload) {
  const pluginId = normalizeId(payload.plugin_id, "plugin-new");
  const name = payload.name || pluginId;
  const version = payload.version || "1.0.0";
  const description = payload.description || "Generated by HELPER1.";
  const tasks = Array.isArray(payload.tasks) && payload.tasks.length > 0 ? payload.tasks : ["run"];
  const roles = Array.isArray(payload.roles) && payload.roles.length > 0 ? payload.roles : ["worker"];

  const manifest = {
    id: pluginId,
    type: "worker",
    version,
    trust: "internal",
    sandbox: "subprocess",
    granted_caps: ["artifact.read", "artifact.write", "bus.emit"],
    state: "active",
    manifest: { description },
    name,
    roles,
    entrypoint: `../../nexusmon/plugins/${pluginId}/index.js`,
    schema: `../../nexusmon/plugins/${pluginId}/schema.json`,
    handlers: Object.fromEntries(tasks.map((task) => [task, `../../nexusmon/plugins/${pluginId}/handlers/${task}.js`])),
  };

  return {
    status: "ok",
    task: "generate",
    generated_at: nowIso(),
    artifacts: [
      { path: `plugins/${pluginId}/manifest.json`, content: toJson(manifest) },
      {
        path: `nexusmon/plugins/${pluginId}/index.js`,
        content:
          "module.exports = async function handler(input) {\n" +
          "  return { status: 'ok', message: 'Generated plugin entrypoint', input };\n" +
          "};\n",
      },
    ],
    summary: {
      plugin_id: pluginId,
      tasks,
      roles,
    },
  };
}

module.exports = generate;
