const crypto = require("crypto");
const { normalizeId, toJson, nowIso } = require("./_shared.js");

async function patchpack(payload) {
  const packId = normalizeId(payload.pack_id || `patchpack-${Date.now()}`, "patchpack-auto");
  const normalizedChanges = payload.changes.map((change) => ({
    path: change.path,
    action: change.action,
    content: typeof change.content === "string" ? change.content : "",
  }));
  const digest = crypto
    .createHash("sha256")
    .update(JSON.stringify(normalizedChanges))
    .digest("hex");

  const pack = {
    id: packId,
    generated_at: nowIso(),
    rationale: payload.rationale || "Generated by HELPER1.",
    apply_mode: "manual-review-required",
    checksum_sha256: digest,
    changes: normalizedChanges,
  };

  return {
    status: "ok",
    task: "patchpack",
    generated_at: pack.generated_at,
    artifacts: [{ path: `prepared_actions/${packId}.json`, content: toJson(pack) }],
    summary: { pack_id: packId, change_count: normalizedChanges.length, checksum_sha256: digest },
  };
}

module.exports = patchpack;
