const { normalizeId, toJson, nowIso } = require("./_shared.js");

async function schema(payload) {
  const title = payload.title;
  const schemaId = normalizeId(title, "generated-schema");
  const generated = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title,
    description: payload.description || "Generated by HELPER1 schema handler.",
    type: "object",
    additionalProperties: false,
    properties: payload.properties,
    required: Array.isArray(payload.required) ? payload.required : [],
    generated_at: nowIso(),
  };

  return {
    status: "ok",
    task: "schema",
    generated_at: generated.generated_at,
    artifacts: [{ path: `config/schemas/${schemaId}.schema.json`, content: toJson(generated) }],
    summary: { schema_id: schemaId, property_count: Object.keys(payload.properties).length },
  };
}

module.exports = schema;
