/**
 * Build extras: generates marketplace.json and README.md
 * Run automatically as part of `npm run build`
 */

import * as fs from 'fs';
import * as path from 'path';
import { PluginManifest, SkillManifest, Marketplace } from './types';

function loadPluginManifests(manifestsDir: string): PluginManifest[] {
  if (!fs.existsSync(manifestsDir)) return [];
  return fs
    .readdirSync(manifestsDir)
    .filter((f) => f.endsWith('.manifest.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(manifestsDir, f), 'utf8')) as PluginManifest);
}

function loadSkillManifests(skillsDir: string): SkillManifest[] {
  if (!fs.existsSync(skillsDir)) return [];
  return fs
    .readdirSync(skillsDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(skillsDir, f), 'utf8')) as SkillManifest);
}

function generateMarketplace(plugins: PluginManifest[], outputPath: string): void {
  const marketplace: Marketplace = {
    generated_at: new Date().toISOString(),
    total: plugins.length,
    plugins: plugins.map((m) => ({
      name: m.name,
      version: m.version,
      title: m.marketplace.title,
      description: m.description,
      category: m.category,
      icon: m.marketplace.icon,
      price: m.marketplace.price,
      tags: m.tags,
      capabilities: m.capabilities,
    })),
  };
  fs.writeFileSync(outputPath, JSON.stringify(marketplace, null, 2));
  console.log(`  marketplace.json: ${plugins.length} plugin(s)`);
}

function generateReadme(
  plugins: PluginManifest[],
  skills: SkillManifest[],
  outputPath: string
): void {
  const pluginRows = plugins
    .map(
      (p) =>
        `| ${p.marketplace.icon} ${p.marketplace.title} | ${p.category} | ${p.description} | ${p.marketplace.price} |`
    )
    .join('\n');

  const skillRows = skills
    .map((s) => `| ${s.name} | ${s.agent} | ${s.description} | ${s.triggers.join(', ')} |`)
    .join('\n');

  const readme = `# SWARMZ Plugin & Skill Marketplace

> Auto-generated by \`npm run build\`. Do not edit manually.

## Plugins

| Plugin | Category | Description | Price |
|--------|----------|-------------|-------|
${pluginRows || '| — | — | No plugins registered yet | — |'}

## Agent Skills

| Skill | Agent | Description | Triggers |
|-------|-------|-------------|---------|
${skillRows || '| — | — | No skills registered yet | — |'}

## Quick Reference

\`\`\`bash
# Install dependencies
npm ci

# Build the project (generates MARKETPLACE.md and marketplace.json)
npm run build

# Validate plugin manifests
npm run plugin:validate

# Generate marketplace.json only
npm run plugin:generate-marketplace

# Create a new plugin
npm run plugin:create -- --name <plugin-name>

# Validate agent skills
npm run skill:validate

# Create a new skill
npm run skill:create -- --name <skill-name>
\`\`\`
`;

  fs.writeFileSync(outputPath, readme);
  console.log(`  MARKETPLACE.md: ${plugins.length} plugin(s), ${skills.length} skill(s)`);
}

function run(): void {
  const cwd = process.cwd();
  const manifestsDir = path.join(cwd, 'plugins', 'manifests');
  const skillsDir = path.join(cwd, 'skills');
  const marketplacePath = path.join(cwd, 'marketplace.json');
  const readmePath = path.join(cwd, 'MARKETPLACE.md');

  const plugins = loadPluginManifests(manifestsDir);
  const skills = loadSkillManifests(skillsDir);

  console.log('Generating build artifacts...');
  generateMarketplace(plugins, marketplacePath);
  generateReadme(plugins, skills, readmePath);
  console.log('Done.');
}

run();
