"""
Tests for {{pascalName}} router.
Generated by Scaffold Bot on {{timestampISO}}
"""

from fastapi.testclient import TestClient


def test_list_{{snakeName}}(client: TestClient):
    response = client.get("/{{kebabName}}/")
    assert response.status_code == 200
    assert "items" in response.json()


def test_get_{{snakeName}}(client: TestClient):
    response = client.get("/{{kebabName}}/test-id")
    assert response.status_code == 200
    assert response.json()["item_id"] == "test-id"


def test_create_{{snakeName}}(client: TestClient):
    response = client.post("/{{kebabName}}/")
    assert response.status_code == 200
    assert response.json()["created"] is True
