"""
{{pascalName}} — FastAPI Router
Generated by Scaffold Bot on {{timestampISO}}
"""

from fastapi import APIRouter

router = APIRouter(prefix="/{{kebabName}}", tags=["{{snakeName}}"])


@router.get("/")
async def list_{{snakeName}}():
    """List all {{name}} items."""
    return {"items": []}


@router.get("/{item_id}")
async def get_{{snakeName}}(item_id: str):
    """Get a single {{name}} item by ID."""
    return {"item_id": item_id}


@router.post("/")
async def create_{{snakeName}}():
    """Create a new {{name}} item."""
    return {"created": True}
